import os
import subprocess
from datetime import datetime

# --- KONFIGURASI ---
FILE_VERSION = "version_info.py"

def get_current_build():
    try:
        if os.path.exists(FILE_VERSION):
            with open(FILE_VERSION, "r") as f:
                for line in f:
                    if "BUILD_NUMBER =" in line:
                        return int(line.split("=")[1].strip())
        return 0
    except:
        return 0

def update_version():
    """Menaikkan versi di file version_info.py"""
    current_build = get_current_build()
    new_build = current_build + 1
    now = datetime.now().strftime("%d-%m-%Y %H:%M")
    
    content = f'''# GENERATED BY PUSH.PY
BUILD_NUMBER = {new_build}
LAST_UPDATED = "{now}"
VERSION_TAG = "v1.{new_build}"
'''
    with open(FILE_VERSION, "w") as f:
        f.write(content)
    return new_build, now

def run_sync():
    print("🚀 --- SISTEM PUSH & AUTO-VERSION BP3MI ---")
    
    # 1. Input pesan dari Bapak
    msg = input("Masukkan Pesan Update (Commit): ") or "Update rutin"
    
    # 2. Update Versi Dulu
    new_build, tgl = update_version()
    print(f"✅ Versi naik ke: v2.{new_build}")

    try:
        # 3. Git Process
        print("⏳ Mengirim ke GitHub...")
        subprocess.run(["git", "add", "."], check=True)
        
        full_msg = f"{msg} [Build v2.{new_build}]"
        subprocess.run(["git", "commit", "-m", full_msg], check=True)
        
        # Gunakan -u agar tidak error upstream lagi
        subprocess.run(["git", "push", "-u", "origin", "main"], check=True)
        
        print(f"\n✨ SUKSES! App v2.{new_build} sudah online.")
    except Exception as e:
        print(f"\n❌ GAGAL: {e}")

if __name__ == "__main__":
    run_sync()